#!/usr/bin/env python3
"""
Flare Tag Dictionary Generator

Generates a tag dictionary mapping tag hashes to human-readable names.
This allows Flare crash dumps to be analyzed with readable tag names.

Usage:
    python3 flare_dict_gen.py tag1 tag2 tag3 > crash.tags
    python3 flare_dict_gen.py --from-file tags.txt > crash.tags

Output format (CSV):
    TagName,HashValue
    Audio,0x1a2b3c4d5e6f7890
    Video,0x2b3c4d5e6f7890ab
"""

import sys
import argparse

def fnv1a_hash(s):
    """
    FNV-1a hash algorithm (64-bit)
    Must match the implementation in emergency_sink.cpp
    """
    FNV_OFFSET = 14695981039346656037
    FNV_PRIME = 1099511628211
    
    hash_value = FNV_OFFSET
    for byte in s.encode('utf-8'):
        hash_value ^= byte
        hash_value *= FNV_PRIME
        hash_value &= 0xFFFFFFFFFFFFFFFF  # Keep it 64-bit
    
    return hash_value

def generate_dictionary(tags):
    """Generate dictionary entries for given tags"""
    print("# Flare Tag Dictionary")
    print("# Format: TagName,HashValue")
    print("# Generated by flare_dict_gen.py")
    print()
    
    for tag in sorted(set(tags)):  # Deduplicate and sort
        hash_value = fnv1a_hash(tag)
        print(f"{tag},0x{hash_value:016x}")

def main():
    parser = argparse.ArgumentParser(
        description='Generate Flare tag dictionary',
        epilog='Example: python3 flare_dict_gen.py Audio Video Network > crash.tags'
    )
    
    parser.add_argument(
        'tags',
        nargs='*',
        help='Tag names to include in dictionary'
    )
    
    parser.add_argument(
        '--from-file',
        '-f',
        type=str,
        help='Read tag names from file (one per line)'
    )
    
    args = parser.parse_args()
    
    tags = []
    
    # Collect tags from command line
    if args.tags:
        tags.extend(args.tags)
    
    # Collect tags from file
    if args.from_file:
        try:
            with open(args.from_file, 'r') as f:
                file_tags = [line.strip() for line in f if line.strip() and not line.startswith('#')]
                tags.extend(file_tags)
        except FileNotFoundError:
            print(f"Error: File '{args.from_file}' not found", file=sys.stderr)
            sys.exit(1)
        except IOError as e:
            print(f"Error reading file: {e}", file=sys.stderr)
            sys.exit(1)
    
    # Validate we have at least one tag
    if not tags:
        print("Error: No tags provided", file=sys.stderr)
        print("Use: python3 flare_dict_gen.py <tag1> <tag2> ...", file=sys.stderr)
        print("Or:  python3 flare_dict_gen.py --from-file tags.txt", file=sys.stderr)
        sys.exit(1)
    
    # Generate dictionary
    generate_dictionary(tags)

if __name__ == '__main__':
    main()
