#pragma once
#ifndef KMAC_NOVA_VERSION_H
#define KMAC_NOVA_VERSION_H

#define NOVA_VERSION_MAJOR 1
#define NOVA_VERSION_MINOR 0
#define NOVA_VERSION_PATCH 0
#define NOVA_VERSION_STRING "1.0.0"

#endif // KMAC_NOVA_VERSION_H
